Pipelines:
  - name: object
    inputs: [RealSenseCameraTopic]
    infers:
      - name: ObjectDetection
        model: /opt/intel/computer_vision_sdk/deployment_tools/intel_models/person-detection-retail-0013/FP16/person-detection-retail-0013.xml
        engine: MYRIAD
        label: to/be/set/xxx.labels
        batch: 1
        confidence_threshold: 0.5
        enable_roi_constraint: true # set enable_roi_constraint to false if you don't want to make the inferred ROI (region of interest) constrained into the camera frame
      - name: PersonReidentification
        model: /opt/intel/computer_vision_sdk/deployment_tools/intel_models/person-reidentification-retail-0076/FP16/person-reidentification-retail-0076.xml
        engine: MYRIAD
        label: to/be/set/xxx.labels
        batch: 1
        confidence_threshold: 0.7
    outputs: [RosTopic, RViz]
    connects:
      - left: RealSenseCameraTopic
        right: [ObjectDetection]
      - left: ObjectDetection
        right: [PersonReidentification]
      - left: PersonReidentification
        right: [RosTopic, RViz]

