Pipelines:
  - name: object
    inputs: [RealSenseCameraTopic]
    infers: # Myriad supports only FP16
      - name: ObjectDetection
        model: /opt/openvino_toolkit/open_model_zoo/model_downloader/object_detection/common/mobilenet-ssd/caffe/output/FP16/mobilenet-ssd.xml 
        engine: MYRIAD
        label: to/be/set/xxx.labels
        batch: 1
    outputs: [RosTopic, RViz]
    confidence_threshold: 0.5
    connects:
      - left: RealSenseCameraTopic
        right: [ObjectDetection]
      - left: ObjectDetection
        right: [RosTopic]
      - left: ObjectDetection
        right: [RViz]
