Pipelines:
- name: object
  inputs: [RealSenseCamera]
  infers:
    - name: ObjectDetection
      model: /opt/openvino_toolkit/open_model_zoo/model_downloader/object_detection/common/mobilenet-ssd/caffe/output/FP32/mobilenet-ssd.xml
      engine: CPU
      label: to/be/set/xxx.labels
      batch: 16
  outputs: [ImageWindow, RosTopic, RViz]
  confidence_threshold: 0.5
  connects:
    - left: RealSenseCamera
      right: [ObjectDetection]
    - left: ObjectDetection
      right: [ImageWindow]
    - left: ObjectDetection
      right: [RosTopic]
    - left: ObjectDetection
      right: [RViz]

OpenvinoCommon:
