Pipelines:
- name: segmentation
  inputs: [Video]
  input_path: /root/video.webm 
  infers:
    - name: ObjectSegmentation
      model: /opt/models/mask_rcnn_inception_v2_coco_2018_01_28/output/frozen_inference_graph.xml
      engine: CPU
      label: to/be/set/xxx.labels
      batch: 1
  outputs: [RosTopic, RViz]
  confidence_threshold: 0.2
  connects:
    - left: Video
      right: [ObjectSegmentation]
    - left: ObjectSegmentation
      right: [RosTopic, RViz]

OpenvinoCommon:

