global_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 1.0
  publish_frequency: 2.0
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05
  transform_tolerance: 0.5
  plugins:
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
  inflation_layer:
    enabled:              true
    cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.
  

