name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Realsense Docker image
      run: docker build docker/realsense2/ --tag intelpengo/realsense2:$(date +%s)
