name: docker-build:realsense2

on:
  push:
    branches: master

jobs:
  build-n-push-realsense2:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker/realsense2/
          file: docker/realsense2/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: intelpengo/realsense2